// Generated by CoffeeScript 1.9.1
(function() {
  var BASE, attr, createiFrame, d, el, err, iframe, input_id, k, l, len, len1, match, options, ref, ref1, ref2, s, scriptEl, session_id, timestamp, url;

  BASE = "https://dbinbox.com";

  scriptEl = document.currentScript;

  options = {};

  ref = scriptEl != null ? scriptEl.attributes : void 0;
  for (k = 0, len = ref.length; k < len; k++) {
    attr = ref[k];
    match = attr != null ? (ref1 = attr.name) != null ? ref1.match(/^data-(.+)$/) : void 0 : void 0;
    if (match && match[1]) {
      options[match[1]] = attr.value;
    }
  }

  if (typeof document.querySelectorAll !== 'function') {
    try {
      d = document;
      s = d.createStyleSheet();
      d.querySelectorAll = function(r, c, i, j, a) {
        a = d.all;
        c = [];
        r = r.replace(/\[for\b/gi, '[htmlFor').split(',');
        i = r.length;
        while (i--) {
          s.addRule(r[i], 'k:v');
          j = a.length;
          while (j--) {
            a[j].currentStyle.k && c.push(a[j]);
          }
          s.removeRule(0);
        }
        return c;
      };
    } catch (_error) {
      err = _error;
      console.error("DBinbox error: couldn't insert querySelectorAll shim", err);
    }
  }

  createiFrame = function(url) {
    var i;
    i = document.createElement("iframe");
    i.setAttribute("src", url);
    i.setAttribute("horizontalscrolling", "no");
    i.setAttribute("allowtransparency", "true");
    i.setAttribute("verticalscrolling", "no");
    i.setAttribute("frameborder", "0");
    i.setAttribute("title", "dbinbox");
    i.setAttribute("scrolling", "no");
    i.setAttribute("tabindex", "0");
    i.setAttribute("width", "100%");
    i.style.width = "100%";
    i.overflow = "hidden";
    i.height = "400px";
    i.border = "0";
    return i;
  };

  timestamp = Date.now();

  if (options) {
    if (options.uploaders && options.page) {
      ref2 = document.querySelectorAll(options.uploaders);
      for (l = 0, len1 = ref2.length; l < len1; l++) {
        el = ref2[l];
        if (!options.debug) {
          el.style.display = "none";
        }
        session_id = options.session || timestamp;
        input_id = el.name || el.id || el.nodeName;
        url = [BASE, options.page, session_id, input_id].join('/').replace(/\s/g, '');
        iframe = createiFrame(url + "?embed=true");
        el.parentNode.insertBefore(iframe, el);
        el.value = url;
        iFrameResize({
          checkOrigin: false
        }, iframe);
      }
    } else {
      console.error('DBinbox.com error: missing script attributes data-uploaders or data-page');
    }
  }

  window.processDbinboxEmbed = function() {
    var a, len2, m, ref3;
    ref3 = document.querySelectorAll('.dbinbox');
    for (m = 0, len2 = ref3.length; m < len2; m++) {
      a = ref3[m];
      url = a.href;
      url = url.replace("/embed/", "/");
      if (url.indexOf('?') === -1) {
        url += "?";
      }
      url += "&embed=true";
      iframe = createiFrame(url);
      a.parentNode.replaceChild(iframe, a);
    }
    return iFrameResize({
      checkOrigin: false
    }, iframe);
  };

  processDbinboxEmbed();

}).call(this);
